pySerialTransfer/pySerialTransfer.py
Resolves #2
Use pySerial tools to determine the list of available serial ports on the system ([docs](https://pyserial.readthedocs.io/en/latest/tools.html)).
Test `port` parameter against full device path and last path fragment, using the os path seperator to split the provided value.
This works for me - it means I can specify my port using shorthand ('serial0', 'ttyUSB0') or whatever, or by full path ('/dev/ttyUSB0'), but those values are tested against those available to pyserial to ensure that they're at least vaguely sane.
I hope this is ok. let me know if it works for you, or if there's any tweaks or changes you'd like to see.
=> Use serial.tools.list_ports to determine valid values

pySerialTransfer/pySerialTransfer.py
It turns out that, whilst useful for most cases, `serial.tools.list_ports.comports()` does not detect `serial0`/`ttyS0`, and this is the default hardwareUART broken out on the GPIO pins.
So, allow the default of using the autodetected list for validation, but allow users to override with the specified parameter value regardless.
=> Allow specification of non auto detected ports

pySerialTransfer/pySerialTransfer.py
When instantiating an instance of Serial with a port specified,
that port will be automatically opened, without a need to explicitly do
so.
Additionally, use of `closed` to determine a port's status seems flawed, as it can erroneously
return `False`, leading to attempts to write to a closed port.
Switching to `is_open` appears to be less error prone.
=> Less connection opening/closing

pySerialTransfer/pySerialTransfer.py
Fix latency issue mentioned in #36 by removing repeated calls to self.connection.read(). On Windows (and maybe other OSes), the PySerial read() function can take approx 1ms, even when only fetching 1 byte. If the payload is 254 bytes, that adds about 1/4 second of latency to each message. This fix removes the multiple calls to read() by fetching the number of bytes listed in the message header all at once.
This also reverts a previous commit on the master branch that fixed the issue, but introduced new issues. That previous commit would throw away any new messages in the buffer and only return the oldest message.
=> Fix Latency Issue

examples/data/Python/rx_data.py
=> fix object size mismatch for str

pySerialTransfer/pySerialTransfer.py
I encountered some strange behaviour during the usage of this library, especially when sending good amounts of data quite often. The status would sometimes return me CRC_ERROR, etc. but after a while the program would simply hang.
I traced this back to the state machine which does not discard packets whose packet length is 0.
This way the fsm would always hang in `find_payload` because the subsequent `if self.payIndex < self.bytesToRec` would never trigger as `self.bytesToRec` was zero.
While the library cannot send packets with zero payload length I believe, this fault can still occur during transmissions.
Since the fsm locks itself out from proceeding to the next states, the library keeps spinning in the same state forever.
My change adds the check to acknowledge a packet as valid if …
=> Fix detection of zero payload length packets

pySerialTransfer/pySerialTransfer.py
These changes add a new feature to pySerialTransfer, allowing the user to specify a write timeout, so that a SerialTimeoutException is raised when the write operation doesn't complete in time.
I built this because in my experiments when sending data using pySerialTransfer to a device where the program wasn't reading from the serial port, the sending code would block forever.
=> add write timeout to serial port

pySerialTransfer/pySerialTransfer.py
When sending strings via SerialTransfer from an Arduino in C++, it is often most practical to work with strings of fixed length, even if the desired content to encode is variable.
When the unused characters in the C++ string have a default value of 0 when encoded as bytes, pySerialTransfer raises an error when it tries to decode the bytes into a string. By removing the unused bytes from the data, pySerialTransfer can succeed in parsing the string.
=> receive string remove trailing 0s

pySerialTransfer/pySerialTransfer.py
Rename the `calc_num_bytes` function to avoid the `num_bytes` variable name shadowing the outer scope.
Addresses #77
=> Rename `num_bytes` function

pySerialTransfer/CRC.py
Rename `CRC()` instance variable to avoid the having the `crc` variable in `calculate` shadowing it.
addresses #81
=> Rename crc instance variable to avoid shadowing

pySerialTransfer/pySerialTransfer.py
Use `isinstance()` to compare types rather than the equality operator for PEP8 compliance and readability
addresses #83
=> Use `isinstance()` to compare types

pySerialTransfer/CRC.py, pySerialTransfer/pySerialTransfer.py
Fix up instances where variables are assigned unecessarily, either a method params, local variables, or iterator variables in list comprehensions.
=> Remove unused variables

pySerialTransfer/pySerialTransfer.py
Fix an issue where attempting to call tx_obj(True) resulted in incorrect values being inserted in tx_buff.
Addresses #91
=> Fix encoding when using `tx_obj` with a value of type `bool`

pySerialTransfer/pySerialTransfer.py
Fix an issue where debug message for `PAYLOAD_ERROR` and `STOP_BYTE_ERROR` statuses are not printed in the `tick()` method.
This is because these statuse values fail to meet the condition `self.debug and not self.status` because they are negative values, unlike `CRC_ERROR` which is 0.
e.g.
```
bool(True and 0)
False
bool(True and -1)
True
```
=> Fix debug print statements in `tick()`

setup.py, tests/test_crc.py, tests/test_py_serial_transfer.py
Adds first cut at a test suite for the `SerialTransfer` and `CRC` classes. It only provides ~85% coverage in total (~90% for `CRC.py` and 84% for `pySerialTransfer.py`). In part this is due to not covering the non core library functionality i.e. the crc `__name__ == "__main__"` code and the helper functions such as `msb`, `lsb` etc.
The coverage is not the full story though, obviously. There are definitely untested code paths here also (which can be seen if pytest is run with coverage turned on), so there are definitely areas for improvement. This feels like a good start however, and I think will go some way to providing a defence against regressions when extending or refactoring the functionality of the library.
It's also worth noting that the content of the tests themselves probably …
=> Add tests for core functionality

pySerialTransfer/pySerialTransfer.py, tests/test_py_serial_transfer.py
* Add a check against all items passed in `set_callbacks` to ensure that they are all callable. raise an `InvalidCallbackList` exception if not, and don't modify the callbacks property
* Add a test to ensure this behaviour
* allow tuples to be passed to `set_callbacks`, as these are also a valid indexable structure.
* Add a test to ensure that non-list|tuple variables passed to `set_callbacks` raises an `InvalidCallbackList` exception if not, and does not modify the callbacks property
=> Test all items are callable when `set_callbacks` is invoked

pySerialTransfer/pySerialTransfer.py
Add  param `packet_id` to `send` method  docstring.
=> Add missing param to docstring

examples/data/Python/rx_data.py, examples/data/Python/tx_data.py, pySerialTransfer/CRC.py, pySerialTransfer/pySerialTransfer.py
In Python 3, you don't need to explicitly inherit from object (i.e., class MyClass(object):) as was the case in Python 2. In Python 3, all classes are new-style classes, so class MyClass: and class MyClass(object): are equivalent.
=> Use Python 3 style classes

pySerialTransfer/pySerialTransfer.py
The `msb`, `lsb`, and `open_ports` functions are unused and can be removed from `pySerialTransfer.py`
Addresses #87
=> Remove unused functions from `pySerialTransfer.py`

pySerialTransfer/pySerialTransfer.py
Somehow missed these in the last pass - `byte_val` and `calc_num_bytes` are unused and can be removed.
=> remove unused functions

pySerialTransfer/__init__.py, pySerialTransfer/pySerialTransfer.py, tests/test_py_serial_transfer.py
This PR replaces all instances of `print` statements in the library with Python's built-in `logging` module. The `print` function, while useful for simple debugging or output, has several disadvantages when used in a library:
1. **Lack of flexibility**: `print` always writes to standard output, and cannot be easily redirected to other destinations like a file or a network socket.
2. **No severity levels**: `print` does not distinguish between different kinds of messages, such as debug, info, warning, and error messages.
3. **No control for library users**: If a library uses `print`, the application using the library cannot easily control when these messages should be output.
On the other hand, the `logging` module provides a flexible framework for emitting log messages from Python …
=> Replace print statements with logging in Python library
